%% Saving
saveDir = {'I:\Users\ENL\Desktop\Vitality_Project_EEG_Data\PreMeditation',...
    'I:\Users\ENL\Desktop\Vitality_Project_EEG_Data\PostMeditation',...
    'I:\Users\ENL\Desktop\Vitality_Project_EEG_Data\Meditator',...
    'I:\Users\ENL\Desktop\Vitality_Project_EEG_Data\Testing'};

workingDir = 'I:\Users\ENL\Documents\GitHub\Vitality-Tactile-Detection\EEG_Simulink\';
movefile(strcat(saveFile,'.mat'),saveDir{medTraining})